# Generated by Django 2.1.3 on 2018-12-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flavors', '0002_flavor_machine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_of_entries', models.IntegerField(default=0)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.Flavor')),
            ],
        ),
    ]
