# Generated by Django 2.1.3 on 2018-12-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_sessions', '0002_trainingsession_create_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_sessions.TrainingSession')),
            ],
        ),
    ]
