# Generated by Django 2.1.3 on 2018-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_trainingsession_create_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='hidden_layers',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
