# Generated by Django 2.1.3 on 2018-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0003_trainingsession_hidden_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(default='done', max_length=10),
        ),
    ]
