# Generated by Django 2.1.3 on 2018-12-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='machine_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
