# Generated by Django 2.1.3 on 2018-12-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_flavor_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='number_of_input_neurons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavor',
            name='number_of_output_neurons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
