# Generated by Django 2.1.3 on 2018-12-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input_data', '0001_initial'),
        ('training_data', '0002_trainingdata_number_of_entries'),
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('layer', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_snapshot', to='snapshots.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data', to='input_data.InputData')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('color', models.FloatField()),
                ('training_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='training_data.TrainingData')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('layer', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_snapshot', to='snapshots.Snapshot')),
            ],
        ),
    ]
