# Generated by Django 2.1.3 on 2018-12-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=5, max_digits=15)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.Snapshot')),
            ],
        ),
    ]
