# Generated by Django 2.1.3 on 2018-12-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
        ('sine', '0002_trainingdata_training_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=20, max_digits=30)),
                ('layer', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=20, max_digits=30)),
                ('layer', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.Snapshot')),
            ],
        ),
    ]
