# Generated by Django 2.1.3 on 2018-12-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0001_initial'),
        ('sine', '0003_bias_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.InputData')),
            ],
        ),
    ]
