# Generated by Django 2.1.3 on 2018-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sine', '0004_inputdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bias',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='value',
            field=models.FloatField(),
        ),
    ]
